services:

  # postgres: # host name
    
  #   image: clothbase-db

  #   restart: always

  #   environment:

  #     - POSTGRES_USER=breno

  #     - POSTGRES_PASSWORD=breno

  #     - POSTGRES_DB=clothbase
    
  #   ports:
  #     - "5432:5432"
  frontend:

    image: frontend

    ports:
     - "8080:8080"

    # volumes:
    #   - type: bind
    #     source: ./container
    #     target: /app
    # working_dir: /app

    volumes:
      - frontend:/app
volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend/container




  






