version: '3.8'

services:
  # api:
  #   build: ./backend  # Adicione esta linha para construir a imagem
  #   restart: always
  #   ports: 
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://breno:breno@postgres:5432/clothbase  # Ambiente essencial
  #   volumes:
  #     - ./backend:/app  # Modificado para bind mount direto
  #   depends_on:
  #     - postgres  # Garante ordem de inicialização

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=breno
      - POSTGRES_PASSWORD=breno
      - POSTGRES_DB=clothbase
    volumes:
      - .db/data:/var/lib/postgresql/data


  # frontend:
  #   build: ./frontend  
  #   ports:
  #     - "3000:3000"  # Porta padrão do React
  #   environment:
  #     - REACT_APP_API_URL=http://api:8000  # Comunicação interna via nome do serviço
  #   depends_on:
  #     - api

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=bbaldassin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SecretPassword
    ports:
      - "8080:80"  # Evitar conflito com outros serviços na porta 80
    depends_on:
      - postgres

# volumes:
#   postgres_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: E:/repos/ClothBase/db/data


  






