version: "1.1"

services:

  postgres:

    image: postgresdb

    environment:

      - POSTGRES_USER=postgres

      - POSTGRES_PASSWORD=postgres

      - POSTGRES_DB=clothbase
    
    ports:
      - "5432:5432"

  






