version: "1.1"

services:

  postgres:

    image: clothbase
    shm_size: 128mb
    restart: always

    environment:

      - POSTGRES_USER=postgres

      - POSTGRES_PASSWORD=postgres
    
    ports:
      - "5432:5432"

  app:

      image: my-python-app
      shm_size: 128mb
  







