services:

  postgres: # host name
    
    image: clothbase-db

    restart: always

    environment:

      - POSTGRES_USER=breno

      - POSTGRES_PASSWORD=breno

      - POSTGRES_DB=clothbase
    
    ports:
      - "5432:5432"

  app:
    
    image: clothbase-app

    stdin_open: true
    tty: true       

    volumes:
      - ~/repos/ClothBase/app:/app

volumes:
  cloth-app:
    name: "source-code"


  






